<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.sms.filter</groupId>
        <artifactId>docker</artifactId>
        <version>0.1.0-SNAPSHOT</version>
    </parent>

    <artifactId>backend-docker</artifactId>
    <packaging>pom</packaging>

    <name>SMS Filter :: Docker :: Backend</name>
    <description>Backend docker image build for SMS Filter</description>

    <dependencies>
        <dependency>
            <groupId>com.sms.filter</groupId>
            <artifactId>api</artifactId>
            <version>${project.version}</version>
            <type>habushu</type>
        </dependency>
    </dependencies>

    <properties>
        <docker.build.command.args>
            --tag smsfilter-backend:${docker.build.image.tag}
            --load
            .
        </docker.build.command.args>
    </properties>

    <build>
        <plugins>
            <!-- Habushu plugin to prepare Python files -->
            <plugin>
                <groupId>org.technologybrewery.habushu</groupId>
                <artifactId>habushu-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>containerize-backend-api</id>
                        <goals>
                            <goal>containerize-dependencies</goal>
                        </goals>
                        <phase>prepare-package</phase>
                        <configuration>
                            <!-- This tells Habushu which Dockerfile to inspect -->
                            <dockerfile>src/main/resources/docker/Dockerfile</dockerfile>
                            <dockerBuilderBase>builder_base</dockerBuilderBase>
                            <dockerFinalBase>final_base</dockerFinalBase>
                            <updateDockerfile>false</updateDockerfile>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            
            <!-- This plugin executes the docker build command -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>exec-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>docker-build</id>
                        <phase>package</phase>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <executable>docker</executable>
                            <commandlineArgs>buildx build --file src/main/resources/docker/Dockerfile --platform ${docker.build.platforms} ${docker.build.command.args}</commandlineArgs>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
